Homework1
jelenanemcic/code-cadets-2021 pull request #7
Opened 2021-05-12 08:26 UTC by jelenanemcic

2021-05-13 08:49 UTC, mbekavac-axilis requested changes

2021-05-13 08:49 UTC, mbekavac-happening commented on homework_1/zad1/fizzbuzz/fizzbuzz_test.go
> +}
please add newline to the end of files

2021-05-13 08:49 UTC, mbekavac-happening commented on homework_1/zad1/fizzbuzz/fizzbuzz_test.go
> +func areSlicesEqual(first []string, second []string) bool {
If you used goconvey (not sure if it was covered on Saturday, but I've seen some other people using it), you would have gotten this for free. Anyway, it was nicely written.

2021-05-13 08:49 UTC, mbekavac-happening commented on homework_1/zad1/fizzbuzz/testCases_test.go
> +func getTestCases() []testCase {
what about negative numbers?

2021-05-13 08:49 UTC, mbekavac-happening commented on homework_1/zad1/main.go
> +	"github.com/pkg/errors"
Please set your IDE to sort the imports. Running `go fmt` should be sufficient.

2021-05-13 08:49 UTC, mbekavac-axilis commented on homework_1/zad1/main.go
> +	result, err := fizzbuzz.PlayFizzBuzz(start, end)
`PlayFizzBuzz` is not too informative - it sounds like a function that does some [side effects](https://softwareengineering.stackexchange.com/questions/40297/what-is-a-side-effect), while it's actually a [pure function](https://en.wikipedia.org/wiki/Pure_function) that gets, calculates or generates FizzBuzz output. Please rename accordingly.

2021-05-13 08:50 UTC, mbekavac-axilis commented on homework_1/zad1/fizzbuzz/fizzbuzz.go
> +func PlayFizzBuzz(start, end int) ([]string, error) {
additional note - please write docstrings for all public functions

2021-05-14 07:56 UTC, jelenanemcic commented on homework_1/zad1/fizzbuzz/testCases_test.go
> +func getTestCases() []testCase {
Thank you, I will add a test case for negative numbers.

2021-05-14 08:42 UTC, mbekavac-axilis approved these changes

2021-05-14 09:16 UTC, merged